server {
    listen 80;
    server_name localhost;
    root /home/maxwell/University/Lumiere;
    index index.php;

    location / {
        try_files $uri $uri/ @rewrite;
    }

    location @rewrite {
        rewrite ^/contacts/?$ /contacts.php last;
        rewrite ^/booking/?$ /booking.php last;
        rewrite ^/masters/?$ /masters.php last;
        rewrite ^/services/?$ /services.php last;
        
        rewrite ^ /index.php last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}